version: '3'
services:
   db:
      image: aot29/test-wiki-db
      container_name: basic-db
      environment:
        MYSQL_ROOT_PASSWORD: secret123
      volumes:
        - "./mount/db:/var/lib/mysql"

   wiki:
      image: aot29/test-wiki-smw
      container_name: basic-wiki
      ports:
         - "80:80"
      links:
         - db

   data: 
      image: aot29/test-wiki-data
      container_name: basic-data
      tty: true

   ontology:
      build: ./
      container_name: ontology-import
      links:
         - wiki
      volumes:
       - "./mount/rdf:/rdf"
       - "./mount/test:/test"
      tty: true
