(TeX-add-style-hook
 "paper"
 (lambda ()
   (TeX-run-style-hooks
    "latex2e"
    "IJCS_template"
    "IJCS_template10")
   (LaTeX-add-labels
    "one"
    "tab1"
    "a1")
   (LaTeX-add-bibitems
    "braley"
    "chhikara"
    "gupta95a"
    "gupta95b"
    "gupta97"
    "gurland94"
    "gurland95"
    "jorgensen"
    "mills71"
    "park99"
    "tang"
    "winkler"
    "wong88"
    "wong89"
    "wong91"))
 :latex)

